version: '3.7'
services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        depends_on:
            - database
        volumes:
            - static:/srv
            - ./backend/myproject:/backend/myproject
            - ./backend/manage.py:/backend/manage.py
        env_file:
            - envvars.env
    database:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    nginx:
        build:
            context: .
            dockerfile: proxy/Dockerfile
        depends_on:
            - backend
        ports:
            - '80:80'
        restart: on-failure
        volumes:
            - ./proxy/conf.d:/etc/nginx/conf.d
            - static:/srv:ro
volumes:
    static:
    postgres-data:




